site_name: task.mk
site_url: https://gh.dayl.in/task.mk
repo_url: https://github.com/daylinmorgan/task.mk
repo_name: daylinmorgan/task.mk
theme:
  name: material
  features:
    - navigation.indexes
  palette:
    - scheme: default
extra_css:
  - stylesheets/extra.css
  - stylesheets/asciinema-player.css
# extra_javascript:
  # - javascripts/asciinema-player.min.js
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
markdown_extensions:
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


