#!/usr/bin/env bash
set -e
LATEST_TASKMK_VERSION="v23.1.1"
VERSION=${TASKMK_VERSION:-$LATEST_TASKMK_VERSION}
printf "Initializing Task.mk (%s) for repo\n" "$VERSION"
if [ -f "./.task.mk" ]; then
	echo "Found local .task.mk."
	echo "Was it already initialized?"
	echo 'Exiting....'
	exit 0
fi
curl -fsSL "https://raw.githubusercontent.com/daylinmorgan/task.mk/$VERSION/task.mk" -o .task.mk
echo .task.mk >>.gitignore
printf '\n-include .task.cfg.mk .task.mk\n' >>Makefile
printf '$(if $(filter help,$(MAKECMDGOALS)),$(if $(wildcard .task.mk),,.task.mk: ; curl -fsSL https://raw.githubusercontent.com/daylinmorgan/task.mk/%s/task.mk -o .task.mk))' \
	"$VERSION" \
	>>Makefile

printf ".task.mk files added to repo\n\n"
echo "Do you want to commit these changes?"
printf "RUN COMMAND: %s (Y/n) " \
	"git add Makefile .gitignore && git commit -m \"chore: initialize .task.mk\""

read -r answer
# if echo "$answer" | grep -iq "^y" ;then
if [ "$answer" != "${answer#[Yy]}" ]; then
	git add Makefile .gitignore && git commit -m "chore: initialize .task.mk"
	echo finished.
else
	echo finished.
fi
